CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    position VARCHAR2(50),
    salary NUMBER(10, 2),
    PRIMARY KEY (id)
);

CREATE TABLE departments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100),
    location VARCHAR2(100),
    PRIMARY KEY (id)
);

CREATE TABLE TestEmpty (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    FullName VARCHAR2(20), 
    Phone VARCHAR2(20)
);

CREATE TABLE Test (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    FullName VARCHAR2(20), 
    Phone VARCHAR2(20)
);

CREATE TABLE Test2 (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    FullName VARCHAR2(20), 
    Phone VARCHAR2(20)
);

INSERT INTO Test (FullName, Phone) VALUES ('foo', '123'), ('foo', '123'), ('John Doe', '123'), ('Jane Smith', '123');

INSERT INTO Test2 (FullName, Phone) VALUES ('Alice Johnson', '123'), ('Bob Brown', '123');

INSERT INTO employees (name, position, salary) VALUES ('Alice', 'Manager', 75000);
INSERT INTO employees (name, position, salary) VALUES ('Bob', 'Engineer', 55000);
INSERT INTO employees (name, position, salary) VALUES ('Charlie', 'Technician', 40000);

INSERT INTO departments (name, location) VALUES ('HR', 'New York');
INSERT INTO departments (name, location) VALUES ('IT', 'San Francisco');
INSERT INTO departments (name, location) VALUES ('Finance', 'Chicago');

COMMIT;
