# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        options: --health-cmd="exit 0" --health-interval=10s --health-retries=5 --health-timeout=2s -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=YourStrongPassword123" -p 1555:1433

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: GenericTableAPI
    - name: Build
      run: dotnet build --no-restore
      working-directory: GenericTableAPI
    - name: Create Database (SQL Server)
      run: |
        # SQL commands to create the tables
        sqlcmd -S localhost,1555 -U SA -P "YourStrongPassword123" -Q "
          CREATE DATABASE TestDB;
        "
    - name: Setup Database (SQL Server)
      run: |
        # SQL commands to create the tables
        sqlcmd -S localhost,1555 -U SA -P "YourStrongPassword123" -Q "USE TestDB; CREATE TABLE Test (ID INT PRIMARY KEY IDENTITY(1,1), Fullname VARCHAR(20), Phone VARCHAR(20)); CREATE TABLE Test2 (ID INT PRIMARY KEY IDENTITY(1,1), Fullname VARCHAR(20), Phone VARCHAR(20)); INSERT INTO Test (Fullname, Phone) VALUES ('John Doe', '1234567890'), ('Jane Smith', '0987654321'); INSERT INTO Test2 (Fullname, Phone) VALUES ('Alice Johnson', '5551234567'), ('Bob Brown', '5559876543');"
    - name: Run application in the background
      run: |
        nohup dotnet run --project GenericTableAPI/GenericTableAPI.csproj &
    #- name: Wait for API server to start
    #  run: sleep 10
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      working-directory: GenericTableAPI
    - name: Cleanup Database
      run: |
        sqlcmd -S localhost,1555 -U SA -P "YourStrongPassword123" -Q "DROP DATABASE TestDB;"

