# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        options: --health-cmd="exit 0" --health-interval=10s --health-retries=5 --health-timeout=2s -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=YourStrongPassword123" -p 1555:1433
      oracle:
        image: gvenzl/oracle-free
        options: >-
          --health-cmd="exit 0"
          --health-interval=10s
          --health-retries=5
          --health-timeout=2s
          -e ORACLE_PASSWORD=oracle123
          -p 1521:1521

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: GenericTableAPI

    - name: Build
      run: dotnet build --no-restore
      working-directory: GenericTableAPI

    # --- SQL SERVER SETUP ---
    - name: Setup SQL Server Database
      run: |
        docker exec -i $(docker ps -q -f ancestor=mcr.microsoft.com/mssql/server:2022-latest) /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "YourStrongPassword123" -C -Q "CREATE DATABASE TestDB"
        docker exec -i $(docker ps -q -f ancestor=mcr.microsoft.com/mssql/server:2022-latest) /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "YourStrongPassword123" -C -Q "
        USE TestDB;
        CREATE TABLE TestEmpty (Id INT PRIMARY KEY IDENTITY(1,1), FullName VARCHAR(20), Phone VARCHAR(20));
        CREATE TABLE Test (Id INT PRIMARY KEY IDENTITY(1,1), FullName VARCHAR(20), Phone VARCHAR(20));
        CREATE TABLE Test2 (Id INT PRIMARY KEY IDENTITY(1,1), FullName VARCHAR(20), Phone VARCHAR(20));
        INSERT INTO Test (Fullname, Phone) VALUES 
          ('foo', '123'), 
          ('foo', '123'), 
          ('John Doe', '123'), 
          ('Jane Smith', '123');
        INSERT INTO Test2 (Fullname, Phone) VALUES 
          ('Alice Johnson', '123'), 
          ('Bob Brown', '123');
        "

    - name: Run app with SQL Server
      run: |
        nohup dotnet run --project GenericTableAPI/GenericTableAPI.csproj &

    - name: Run Tests on SQL Server
      run: dotnet test --no-build --verbosity normal
      working-directory: GenericTableAPI

    # --- ORACLE SETUP ---
    - name: Setup Oracle Database Schema
      run: |
        echo "Creating Oracle tables and inserting test data"
        docker exec -i $(docker ps -q -f ancestor=gvenzl/oracle-free) bash -c "
        echo \"CREATE TABLE TestEmpty (
                    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    FullName VARCHAR2(20),
                    Phone VARCHAR2(20)
                  );
        CREATE TABLE Test (
                    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    FullName VARCHAR2(20),
                    Phone VARCHAR2(20)
                  );
        CREATE TABLE Test2 (
                    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    FullName VARCHAR2(20),
                    Phone VARCHAR2(20)
                  );
        INSERT INTO Test (FullName, Phone) VALUES ('foo', '123');
        INSERT INTO Test (FullName, Phone) VALUES ('foo', '123');
        INSERT INTO Test (FullName, Phone) VALUES ('John Doe', '123');
        INSERT INTO Test (FullName, Phone) VALUES ('Jane Smith', '123');
        INSERT INTO Test2 (FullName, Phone) VALUES ('Alice Johnson', '123');
        INSERT INTO Test2 (FullName, Phone) VALUES ('Bob Brown', '123');
        COMMIT;\" | sqlplus SYSTEM/oracle123@//localhost:1521
        "


    - name: Run app with Oracle
      run: |
        pkill dotnet || true
        nohup dotnet run --project GenericTableAPI/GenericTableAPI.csproj &
      env:
        ConnectionStrings__DefaultConnection: "User Id=SYSTEM;Password=oracle123;Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))"

    - name: Run Tests on Oracle
      run: dotnet test --no-build --verbosity normal
      working-directory: GenericTableAPI
