# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: GenericTableAPI
    - name: Build
      run: dotnet build --no-restore
      working-directory: GenericTableAPI
    - name: Run application in the background
      run: |
        nohup dotnet run --project GenericTableAPI/GenericTableAPI.csproj &
    - name: Wait for API server to start
      run: sleep 10
    - name: Verify API is reachable
      run: curl -v http://localhost:5066/api/tables/test
    - name: Run tests
      run: dotnet test --no-build --verbosity normal
      working-directory: GenericTableAPI

